# Generated by Django 5.2.17 on 2026-08-18 11:22

import django.db.models.deletion
import game_engine.logic
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room_name",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("LOCAL", "Local Pass & Play"),
                            ("PVAI", "Player vs AI Bot"),
                            ("PVP", "Online Multiplayer"),
                        ],
                        default="PVP",
                        max_length=10,
                    ),
                ),
                (
                    "ai_role",
                    models.CharField(
                        choices=[("SHEEP", "Sheep / Goat"), ("LION", "Lion / Tiger")],
                        default="LION",
                        max_length=10,
                    ),
                ),
                (
                    "ai_difficulty",
                    models.CharField(
                        choices=[
                            ("EASY", "Easy"),
                            ("MEDIUM", "Medium"),
                            ("HARD", "Hard"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                (
                    "board",
                    models.JSONField(default=game_engine.logic.create_initial_board),
                ),
                ("game_phase", models.CharField(default="PLACEMENT", max_length=15)),
                (
                    "current_turn",
                    models.CharField(
                        choices=[("SHEEP", "Sheep / Goat"), ("LION", "Lion / Tiger")],
                        default="SHEEP",
                        max_length=10,
                    ),
                ),
                ("unplaced_sheep", models.IntegerField(default=20)),
                ("captured_sheep", models.IntegerField(default=0)),
                (
                    "game_status",
                    models.CharField(
                        choices=[
                            ("IN_PROGRESS", "In Progress"),
                            ("LIONS_WON", "Lions Won"),
                            ("SHEEP_WON", "Sheep Won"),
                        ],
                        default="IN_PROGRESS",
                        max_length=15,
                    ),
                ),
                ("move_number", models.IntegerField(default=0)),
                ("state_version", models.IntegerField(default=1)),
                ("move_history", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "player_lion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="games_as_lion",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "player_sheep",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="games_as_sheep",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
